### ISSUE TITLE
Previous - Next post

### ISSUE THREAD

**Issue by omelki** [FadiZahhar/TOB#19]
The issue here is whenever i click on a post from the homepage, I get the next post of 
"ITS CATEGORY". Per example the latest post is "Shanklish" on the homepage, when you click it, you will have at the end of the article "Previous Zaatar salad"

We have two issues here: 

First it should be "NEXT". 

Second the next post should be the one that was posted before the last one on the "HOMEPAGE" and not from its category.

However If I am in the category page like "salad" and I click on the latest post, then the next post should be the one that was posted before the last one on the "SALAD Category" and not from the homepage this time!

**Comment by pro-freelancer** [comment]
The way it is I can't tell wish category is belong. The solution is a category permalink flag that I can retrieve from the url so I can query the related post. You need to set the settings of the website to read the format of category and post so I can take it from here.
